title: "女神科網有限公司"
#baseURL: "https://localhost:1313"
baseURL: "https://playverv.github.io/GoddessWeb"
languageCode: "zh-tw"
defaultContentLanguage: "zh-tw"
defaultContentLanguageInSubdir: true
theme: "github.com/kdevo/osprey-delight"
tags: ["女神科網", "goddess", "美妝", "保養品"]
canonifyURLS: true
#googleAnalytics: ""
disableKinds: ["taxonomy"]
enableEmoji: true
pygmentsUseClasses: true

module:
  imports:
  - path: github.com/kdevo/osprey-delight
  - path: github.com/hugo-mods/icons
  - path: github.com/hugo-mods/lazyimg
  - path: github.com/hugo-mods/release-notify

## Generic theme parameters:
Params:
  author: "Goddess"
  description: "女神科網"

  header_use_video: false

  # logoBig appears at the top of the page. Use a path relative to the assets dir for auto-resizing. 
  logoBig: "/images/Goddess-logo.png"

  # logoSmall is the logo that will be shown in the left corner of the nav bar.
  #   Use a path relative to the assets dir for auto-resizing.
  logoSmall: "/images/Goddess-logo-small.png"
  
  # background can optionally be specified as an image layer behind logoBig at the top of the page (parallax effect).
  background: "/images/background.webp"
  
  # opengraphImage specifies the image that is shown when previewing the site in a messenger or Google Search.
  opengraphImage: "/images/Goddess-logo.png"

  # favicon of the site (e.g. smaller version of logoSmall).
  favicon: "/images/favicon.png"

  # theme your site by choosing one of the themes under assets/sass/themes:
  #   - delight is the light version of osprey-delight
  #   - dedark is the dark version of "delight"
  #   - origin is the legacy version (similar to https://github.com/tomanistor/osprey)
  theme: "delight"

  # tagline (followed by a cursor) is shown at the top, below the logo
  #tagline: "Welcome!"
  # mdTagline can be used instead to specify the tagline in Markdown for more customizability.
  #   Note that {cursor} is a placeholder and will be replaced by the actual cursor HTML when rendering.
  mdTagline: "# Welcome!\n ## 女神科網"

  # enforceSinglePage will enforce redirection to the baseURL for all sub-directories/-pages.
  #   Example: If you create about.md, Hugo will also create a '/about/index.html' which might not be what you want for a *single* page site. 
  #   If this switch is enabled, all these "orphan" files will contain only a redirect directive.
  enforceSinglePage: false

  #使用i18n來取得資訊
  address: "com-address"
  telephone: "com-tel"
  email: "com-email"
  copyright: true

  # credit to the theme. If you want to support the theme by please leave this in, it's kept very tiny and short.
  credit: false

## Social links in footer:
##   The type specifies the icon to use. For more information, see: 
##   https://github.com/kdevo/osprey-delight/blob/dev/CUSTOMIZING.md#icons
  Social:
  - type: facebook
    url: "https://facebook.com"
  - type: instagram
    url: "https://instagram.com"
  - type: youtube
    url: "https://youtube.com"

## Additional theme features:
  Feat:
    # ajaxBasin requires Basin setup for a free contact form (see instructions in README).
    ajaxBasin: "https://usebasin.com/f/{YOUR-12-CHAR-FORM-KEY-HERE}"

    # useStructuredData for your own https://schema.org/Person (SEO-friendly).
    #   This will be auto-generated dependent on the information you provide in this configuration.
    useStructuredData: false

    # structuredDataGitHubUser will tell the theme to use your USERNAME for querying the GitHub API to fetch more information about you for structured data.
    #   This will use information that is publically available about your GitHub user profile at https://api.github.com/users/{USERNAME}.
    #structuredDataGitHubUser = "USERNAME"

    # useTermynal enables Termynal (https://github.com/ines/termynal), a small JS library for showing a terminal "animation" from within your gallery item.
    #   The library has been stripped-down to a minimum to only have the necessary functionality.
    useTermynal: true

    googleTagManager: ""

    # notifyOnNewThemeVersion enables a notification for every new minor/major version of this theme.
    #   Whenever there is a new one, a warning is printed to console.
    notifyOnNewThemeVersion: true
  
    useLazySizes: true

    # 匯入相關js lib，如果link是網址 http 則使用 <script src="" type="javascript"></script>
    # 如果是相對路徑，則會使用js.Build打包，因為使用了resources.Get，所以檔案位置必須在assets資料夾中
    plugins:
    - link: "js/vendor/jquery.min.js"
    - link: "js/vendor/jquery.scrollex.min.js"

  # Image resizing can be configured here (see README for more info):
  Image:
    Logo:
      resize: "600x"

    Gallery:
      resize: "600x"

    Background:
      resize: "1920x"
      resizeLQIP: "256x"

  # Advanced configuration for lazyimg module (comment out if needed):
  # lazyimg:
  #   resizer: auto
  #   renderer: lqip-webp

  #   # Resizer options:
  #   lqipSize: "120x Gaussian"
  #   maxSize: "1920x"
  #   responsiveSizes: ["320x", "640x", "768x", "1024x", "1366x", "1600x", "1920x"]
  #   resizeOptions: "Lanczos q95"

  #   # Renderer options:
  #   #class: ""
  #   #alt: ""
  #   noscript: true
      

## Menu items are automatically added to navbar.
##   See: https://gohugo.io/content-management/menus/#add-content-to-menus
##   * identifier controls the section type (and therewith the appearence).
##   * url must be an anchor, for smooth scrolling to it when clicking on the menu item.
Menu:
  Main:
    - name: "About"
      identifier: about
      url: "/#about"
      weight: 1
    - name: "Product"
      identifier: gallery
      url: "/#work"
      weight: 2
    - name: "News"
      identifier: blog
      url: "/#blog"
      weight: 3
    - name: "Contact"
      identifier: contact
      url: "/#contact"
      weight: 4
    - name: "HR"
      identifier: hr
      url: "/hr"
      pre: '<i class="icon icon-rocket"></i>'
      weight: 5
    # - name: ""
    #   # pre makes it possible to use arbitrary HTML before the name, e.g. referencing icons here is possible:
    #   pre: '<svg class="icon"><use xlink:href="#icon-external"/></svg>&nbsp;'
    #   url: "https://pyotek.dev"


## 多語系設定
languages:
  zh-tw:
    contentDir: content/zh-tw
    disabled: false
    languageCode: zh-tw
    languageDirection: ltr
    languageName: 繁體中文
    title: 女神科網有限公司
    weight: 1
  en:
    contentDir: content/en
    disabled: true
    languageCode: en-US
    languageDirection: ltr
    languageName: English
    title: Goddess
    weight: 2